#ifndef _P2P_CONSTANTS
#define _P2P_CONSTANTS

#define STANDARD_BODY_SIZE 100
#define PEER_NAME_SIZE 10
#define CONTENT_NAME_SIZE 10
#define DATA_BODY_SIZE 1024
#define MAX_CONTENT_LISTING_LENGTH 5

#endif